# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: local

  resources:
    add-mappings: true

url:
  api:
    account:
      signup: /api/account/signup
      signin: /api/account/signin
      refresh: /api/account/refresh
    financialSupport:
      findAll: /api/financial-supports
      findByRegion: /api/financial-supports/by/region
      modify: /api/financial-supports/{id}

      file:
        load: /api/financial-supports/file/load-support-data
      search:
        higherLimit: /api/financial-supports/search/regions/higher-limit
        instituteLeastRate: /api/financial-supports/search/institute/least-rate
